#12 implementado la interaccion basica del jugador con su entorno
isaiasbrianojasso/EquipoDinamita pull request #13
Opened 2020-12-21 20:42 UTC by iFelixP

Agregué la interacción del jugador con lo básico para el funcionamiento del juego, como:
- Se puede chocar con los muebles y los muros.
- Se puede empujar algunos objetos como los taburetes (también colisionan con otros objetos y los muros).
- Puede recolectar objetos que estén dentro de los muebles (los almacena en una lista de objetos clave).
- Al mantener presionada la tecla "c" el jugador puede correr.
- Las puertas que se encuentran cerradas con llave solo se abren con la llave correcta.

Realice algunos cambios pequeños como:
- El botón de nuevo juego ahora llama a la clase "Game".
- Los botones del menú de inicio ahora están en español (haha).
- El titulo del menú de inicio es una imagen separada.
- Las clases de records y controles ahora tienen imagen de fondo y regresan al menú principal al presionar "Esc".
- La música del menú la dejé comentada por el momento para que no moleste.

También agregué una clase llamada "Dialogues" para almacenar todos diálogos que se vallan a utilizar durante el juego.

La clase "Game" tiene una lista de "Muebles" para almacenar todos los objetos clave (como puertas bloqueadas o muebles que contengan curas u otros objetos) y evitar que el estado se pierda cuando el jugador salga de la sala (por ejemplo, si un jugador ya tomó una cura que se encontraba en un librero, al salir y volver a entrar, no se vuelva a generar otra cura en ese librero).

2020-12-28 23:03 UTC, iuresti requested changes

2020-12-28 23:03 UTC, iuresti commented on ControlsButton.java
>          if(buttonActive == true && buttonPressed == true) {
Ya que `buttonActive` y `buttonPressed` son variables booleanas, es redundante escribir ` == true`, es suficiente: 
```
if(buttonActive && buttonPressed) {
   ....
}
```

2020-12-28 23:03 UTC, iuresti commented on Door.java
> +                textbox.displayDescription("Puerta " + Integer.toString(doorNumber),description);
Me gusta cómo usaron la excepción aquí !

2020-12-28 23:03 UTC, iuresti commented on Player.java
> +        if(collisionObject.getClass() == Door.class) {
para saber si un objeto es de una clase en particular utilicen el operador `instanceof `

```
if(collisionObject instanceof Door)
```

2020-12-28 23:03 UTC, iuresti commented on TextBox.java
> +        while(!Greenfoot.isKeyDown("x")) {
Usar ciclos para esperar eventos en los actores, provoca que los otros actores no se ejecuten... recuerden que el método `act` ya está dentro de un ciclo ... si ven en su juego que todo se pone lento puede ser por este ciclo, tendrían que cambiar la lógica. Si no les afecta porque en el punto en que lo usan no hay más actores, entonces no le veo necesidad de cambiarlo

2020-12-29 00:57 UTC, iFelixP commented on ControlsButton.java
>          if(buttonActive == true && buttonPressed == true) {
Corregido

2020-12-29 00:57 UTC, iFelixP commented on Player.java
> +        if(collisionObject.getClass() == Door.class) {
Corregido

2020-12-29 00:57 UTC, iFelixP commented on TextBox.java
> +        while(!Greenfoot.isKeyDown("x")) {
De hecho lo que esperamos es que no se ejecute nada más mientras una caja de texto se este mostrando sino hasta que el jugador presione una tecla para quitarla y continuar con el juego.

2021-01-07 14:20 UTC, iuresti approved these changes

2021-01-07 14:30 UTC, merged