Escenarios
isaiasbrianojasso/EquipoDinamita pull request #15
Opened 2020-12-24 04:17 UTC by iFelixP

Agregué las habitaciones con las que el jugador deberá de interactuar así como también las puertas clave que deberán ser desbloqueadas para avanzar.

Algunos cambios que realicé el el código anterior fueron:
- Arreglé la colisión de los objetos movibles.
- Los objetos movibles ya no muestran ningún cuadro de dialogo al presionar "X".
- Cambios en la detección de colisión del jugador.
- Arreglado el que el jugador almacenara objetos null indefinidamente lo que generaba nullPointerException.

2020-12-28 23:36 UTC, iuresti requested changes
Añadí algunos comentarios, pero como se traslapa con el PR más antiguo, completo la revisión una vez que el primer PR esté aprobado y mezclado

2020-12-28 23:36 UTC, iuresti commented on Character.java
> +    public GreenfootImage []spritesRight = new GreenfootImage[4];
Por qué estos atributos son públicos?... cámbienlo para que tenga la menor visibilidad posible.

2020-12-28 23:36 UTC, iuresti commented on Dialogues.java
> +public class Dialogues
Para este caso de uso, es mejor utilizar constantes en lugar de métodos:

```
public class Dialogues{
    public static final String LINE_FIRST_KEY = "Parece haber algo detras de uno de estos libros";
    public static final String LINE_LOCKED_DOOR = "Está cerrada con llave, tal vez deba revisar alrededor";
    public static final String LINE_WAREHOUSE = "No parece que se pueda abrir por ahora";
    public static final String LINE_DOOR_2A = "Creo ver algo adentro, debería haber una forma de entrar";
    public static final String LINE_DOOR_KITCHEN_2A = "La puerta está cerrada desde dentro";
    public static final String LINE_STAIRS_BLOCKED = "Parece que las escaleras están bloqueadas";
    public static final String LINE_ELEVATOR_NO_WORKS = "Le hace falta los botones para funcionar, tal vez haya alguno cerca";
    public static final String LINE_1 = "Parece haber algo debajo de esta cama";
}
```

2020-12-28 23:36 UTC, iuresti commented on Door.java
> +        switch(doorType) {
por el número de opciones parece quedar mejor un `if`

2020-12-28 23:36 UTC, iuresti commented on Door.java
> +            if(keyObject.getClass() == Key.class && ((Key)keyObject).getNumber().equals(doorNumber)) {
Usa: `keyObject instanceof Key`

2020-12-28 23:36 UTC, iuresti commented on FirstLevel.java
> +        //elevatorThirdFloor.setLocked(true);
Elimina código comentado

2020-12-28 23:36 UTC, iuresti commented on Floor.java
> +                setImage(new GreenfootImage("./images/extras/dark_wood_floor.jpg"));
Podrías declarar los objetos GreenfootImage como estáticos y reutilizarlos aquí .. eso ahorraría memoria y procesamiento

2020-12-28 23:36 UTC, iuresti commented on Forniture.java
> +    public KeyObject object;
Si deseas que estos atributos puedan ser usados desde los hijos el modificador de acceso correcto es `protected`, los atributos no deben ser públicos

2020-12-28 23:36 UTC, iuresti commented on Game.java
> +    public FirstLevel firstLevel = new FirstLevel();
Atributos públicos

2020-12-29 04:44 UTC, iFelixP commented on Character.java
> +    public GreenfootImage []spritesRight = new GreenfootImage[4];
Corregido

2020-12-29 04:45 UTC, iFelixP commented on Dialogues.java
> +public class Dialogues
Corregido

2020-12-29 04:45 UTC, iFelixP commented on Door.java
> +        switch(doorType) {
Corregido

2020-12-29 04:45 UTC, iFelixP commented on Door.java
> +            if(keyObject.getClass() == Key.class && ((Key)keyObject).getNumber().equals(doorNumber)) {
Corregido

2020-12-29 04:45 UTC, iFelixP commented on FirstLevel.java
> +        //elevatorThirdFloor.setLocked(true);
Corregido

2020-12-29 04:45 UTC, iFelixP commented on Floor.java
> +                setImage(new GreenfootImage("./images/extras/dark_wood_floor.jpg"));
Corregido

2020-12-29 04:45 UTC, iFelixP commented on Forniture.java
> +    public KeyObject object;
Corregido

2020-12-29 04:45 UTC, iFelixP commented on Game.java
> +    public FirstLevel firstLevel = new FirstLevel();
Corregido

2021-01-07 14:20 UTC, iuresti approved these changes

2021-01-07 14:31 UTC, merged